def exceptionsHandling(e):
    print("Error occured!")
    print(type(e))
    print(e)

class qException(Exception):
    pass